DROP TABLE IF EXISTS gemstones CASCADE;
DROP TABLE IF EXISTS my_users CASCADE;


CREATE TABLE my_users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	email VARCHAR NOT NULL UNIQUE,
	password_hash VARCHAR NOT NULL
);

CREATE TABLE gemstones (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT,
	description VARCHAR NOT NULL,
	is_beautiful BOOLEAN NOT NULL DEFAULT(true),
	qty INT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES my_users(id)
);