DROP TABLE IF EXISTS fruits;
DROP TABLE IF EXISTS my_users;


CREATE TABLE my_users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	email VARCHAR NOT NULL UNIQUE,
	password_hash VARCHAR NOT NULL
);

CREATE TABLE fruits (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT,
	description VARCHAR NOT NULL,
	is_delicious BOOLEAN NOT NULL DEFAULT(false),
	qty INT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES users(id)
);